linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - misspell
    - goimports
    - golint
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 35