project_name: bigfile

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  -
    id: bigfile
    main: ./artisan/bigfile.go
    binary: bigfile
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "bigfile/bigfile:latest"
        - "bigfile/bigfile:{{ .Tag }}"
        - "bigfile/bigfile:{{ .Tag }}-{{ .Env.GO_VERSION }}"
        - "bigfile/bigfile:v{{ .Major }}"
      skip_push: false
