language: go

branches:
  only:
    - master
    - dev

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - go: 1.12.x

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://goproxy.io
    - BIGFILE_DEFAULT_DB_USER=root
    - BIGFILE_DEFAULT_DB_PWD=
    - BIGFILE_MODE=dev

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

go_import_path: github.com/bigfile/bigfile

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bigfile;'
  - go run artisan/bigfile.go migrate:refresh
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/mgechev/revive
  - go get -u github.com/client9/misspell/cmd/misspell

script:
  - misspell -error ./
  - diff <(goimports -l .) <(printf "")
  - diff <(revive ./...) <(printf "")
  - golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)