language: go

branches:
  only:
    - master
    - dev

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env:
        - GO111MODULE=on
        - GOPROXY=https://goproxy.io

env:
  global:
    - BIGFILE_DEFAULT_DB_USER=root
    - BIGFILE_DEFAULT_DB_PWD=
    - BIGFILE_MODE=dev

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

go_import_path: github.com/bigfile/bigfile

before_script:
#  - echo "export BIGFILE_DEFAULT_DB_USER=root" >> ~/.bashrc
#  - echo "export BIGFILE_DEFAULT_DB_PWD=" >> ~/.bashrc
#  - echo "export BIGFILE_MODE=dev" >> ~/.bashrc
#  - source ~/.bashrc
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bigfile;'
  - go run artisan/bigfile.go migrate:refresh

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)